import { NgModule } from '@angular/core';
import {
    MatMenuModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatIconModule,
    MatToolbarModule,
    MatFormFieldModule,
    MatTabsModule,
    MatGridListModule,
    MatSelectModule,
    MatInputModule,
    MatCardModule,
    MatStepperModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatTableModule,
    MatPaginatorModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatSidenavModule
} from '@angular/material';

@NgModule({
    imports: [
        MatMenuModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatIconModule,
        MatToolbarModule,
        MatFormFieldModule,
        MatTabsModule,
        MatGridListModule,
        MatSelectModule,
        MatInputModule,
        MatCardModule,
        MatStepperModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatListModule,
        MatTableModule,
        MatPaginatorModule,
        MatCheckboxModule,
        MatSlideToggleModule,
        MatSidenavModule
    ],
    exports: [
        MatMenuModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatIconModule,
        MatToolbarModule,
        MatFormFieldModule,
        MatTabsModule,
        MatGridListModule,
        MatSelectModule,
        MatInputModule,
        MatCardModule,
        MatStepperModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatListModule,
        MatTableModule,
        MatPaginatorModule,
        MatCheckboxModule,
        MatSlideToggleModule,
        MatSidenavModule
    ]
})
export class AppMaterialModule { }